DELETE FROM hat;
DELETE FROM ergibtEntfernung;
DELETE FROM fliegt;
DELETE FROM rechnung;
DELETE FROM belegung;
DELETE FROM kunde;
DELETE FROM touristenattraktion;
DELETE FROM bild;
DELETE FROM ferienwohnung;
DELETE FROM flughafen;
DELETE FROM adresse;
DELETE FROM ort;
DELETE FROM land;
DELETE FROM fluggesellschaft;
DELETE FROM zusatzausstattung; 
DELETE FROM bankverbindung;
commit;
